-- Create waitlist table
create table if not exists public.waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

-- Create plan_waitlist table
create table if not exists public.plan_waitlist (
  id bigint generated by default as identity primary key,
  email text not null unique,
  selected_plan text not null,
  event_volume text,
  current_tool text,
  created_at timestamp with time zone not null default timezone('utc'::text, now())
);

-- Enable Row Level Security (RLS)
alter table public.waitlist enable row level security;
alter table public.plan_waitlist enable row level security;

-- Allow public (anonymous) inserts to waitlist
create policy "Allow anonymous inserts to waitlist"
  on public.waitlist
  for insert
  with check (true);

-- Allow public (anonymous) inserts to plan_waitlist
create policy "Allow anonymous inserts to plan_waitlist"
  on public.plan_waitlist
  for insert
  with check (true);
